### PR TITLE
Added Laravel 5 support

### PR DESCRIPTION
**Pull request by wemersonjanuario**
Laravel 5 support is now available. Updated README file for new way to publish config.
Thanks!

### CODE REVIEW

**Comment by barbushin** [comment]
Thanks, man, you did a great job! But...

1. `"php-console/laravel-service-provider": "dev-laravel-5"` - it's wrong. There must be release version, not dev.
2. You should keep original code style, means you should use `tabs` for indentions, not `spaces`. And braces on same line as method definition http://i.hizliresim.com/BZpJgj.png
3. `php artisan vendor:publish` is wrong. You can't ask users to publish configs of all vendors!
4. And... is there backward compatibility with Laravel 4? I don't think so...

May be we should move Laravel 5 service provider to separate repo?

BTW, what do you think about https://github.com/barbushin/php-console-laravel/issues/5#issuecomment-77589435?

**Comment by wemersonjanuario** [comment]
Hi, thanks for you feedback, Sorry for this. I added a new commit. Please check if its ok now.
About the new repo for L5 compatibility you can do it or not.  Or create a new 2.0 release for L5 and keep 1.x for L4.

**Comment by barbushin** [comment]
That's a good idea for Release 2.* for Laravel 5. Thanks! But you still use `spaces` instead of `tabs` for indention. See https://github.com/barbushin/php-console-laravel/pull/6/files

Please use `tabs`.

**Comment by wemersonjanuario** [comment]
I will check my IDE configs and try to fix it. Thanks

--
<http://www.gestorwebin.com/>
www.gestorwebin.com <http://extjs/extjs/docs/www.gestorwebin.com/>
*Wemerson Januario*

**Comment by wemersonjanuario** [comment]
Friend I think the identation is correct with tab. take a look at my IDE settings. What is wrong? Could you help me?
captura de tela 2015-04-10 14 19 24

**Comment by wemersonjanuario** [comment]
Is not possible to realease a version with my commits?

**Comment by barbushin** [comment]
Hey :)

Correct indention is to use `tabs`. See https://github.com/barbushin/php-console-laravel/pull/6/files because you replaced all tabs to spaces GIT thinks that you changed all files content. See `/src/config/config.php` it looks like you changed all file, but all you did - just reformatted it replacing `tabs` to `spaces`.

You should revert all formattings and enable using tabs for indention in your IDE. 

It's important rule about contributing to any open source project. You should keep original code formatting style.

**Comment by frankdors** [comment]
Whow i use in my composer this pull request?

**Comment by wemersonjanuario** [comment]
@frankdors  especify dev-laravel-5 and add my fork repository.
Here is an example how to use it in your composer.json file


"repositories": [
      {
      "type": "git",
      "url": "https://github.com/wemersonjanuario/php-console-laravel"
    }
  ],
"require": {
"php-console/laravel-service-provider": "dev-laravel-5"
}

**Comment by frankdors** [comment]
@wemersonjanuario Thanks!

**Comment by younes0** [comment]
no merge yet?

**Comment by project-hub** [comment]
Hi guys! @barbushin (Sergey) don't have a free time to check it, he asked me to merge it. Anybody test it? Does it works without any bugs?

**Comment by project-hub** [comment]
And what about Laravel 4? It will still works?

**Pull request merged**
